"""Analysis and reporting pipeline for dense delay experiments."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
import json

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from egtrqc.config import DelayConfig, KernelConfig, ReproducibilityConfig, SimulationConfig
from egtrqc.diagnostics import audit_delay_definition, audit_single_advance_per_step
from egtrqc.geometry import build_octa_graph
from egtrqc.io import write_result_json
from egtrqc.octa_dense_model import DenseReducedOCTAModel, DenseReducedOCTAModelConfig
from egtrqc.quantum import ensure_density, matrix_log_psd
from egtrqc.simulator import DelayAwareSimulator, SimulationResult


@dataclass(frozen=True, slots=True)
class DenseAnalysisConfig:
    """Configuration for dense delay analysis runs.

    Attributes:
        delays: Delay values to evaluate.
        total_time: Final physical time.
        dt: Discrete time step.
        seed: Deterministic seed.
        output_dir: Directory where artifacts are written.
    """

    delays: tuple[int, ...]
    total_time: float
    dt: float
    seed: int
    output_dir: Path


@dataclass(frozen=True, slots=True)
class DenseAnalysisArtifacts:
    """Paths generated by the dense delay analysis pipeline."""

    output_dir: Path
    manifest_path: Path
    timeseries_csv: Path
    summary_csv: Path
    report_markdown: Path
    plot_files: tuple[Path, ...]



def run_dense_delay_analysis(config: DenseAnalysisConfig) -> DenseAnalysisArtifacts:
    """Run dense delay simulations and build report artifacts.

    Args:
        config: Analysis configuration.

    Returns:
        Paths to the generated artifacts.
    """
    output_dir = config.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    all_rows: list[dict[str, float | int | str | bool]] = []
    summary_rows: list[dict[str, float | int | str | bool]] = []
    manifest: list[dict[str, object]] = []

    dense_model = DenseReducedOCTAModel(build_octa_graph(), DenseReducedOCTAModelConfig())
    reference_state = dense_model.reference_state()

    for delay in config.delays:
        sim_config = SimulationConfig(
            total_time=config.total_time,
            dt=config.dt,
            delay=DelayConfig(delay_steps=int(delay), kernel=KernelConfig(kind="delta")),
            reproducibility=ReproducibilityConfig(seed=config.seed, store_every=1, output_dir=output_dir),
            label=f"dense-delay-{delay}",
        )
        model = DenseReducedOCTAModel(build_octa_graph(), DenseReducedOCTAModelConfig())
        result = DelayAwareSimulator(model=model, config=sim_config).run()
        artifact_path = write_result_json(result, output_dir / f"dense_delay_{delay}.json")
        delay_audit = audit_delay_definition(result)
        advance_audit = audit_single_advance_per_step(result)
        timeseries_rows, summary_row = _result_to_rows(result, reference_state=reference_state, delay=delay)
        all_rows.extend(timeseries_rows)
        summary_rows.append(summary_row)
        manifest.append(
            {
                "delay_steps": int(delay),
                "artifact": str(artifact_path),
                "delay_audit": asdict(delay_audit),
                "single_advance_audit": asdict(advance_audit),
                "summary": summary_row,
            }
        )

    timeseries_df = pd.DataFrame(all_rows)
    summary_df = pd.DataFrame(summary_rows).sort_values("delay_steps", kind="mergesort")

    timeseries_csv = output_dir / "dense_delay_timeseries.csv"
    summary_csv = output_dir / "dense_delay_summary.csv"
    manifest_path = output_dir / "manifest.json"
    report_markdown = output_dir / "REPORT.md"

    timeseries_df.to_csv(timeseries_csv, index=False)
    summary_df.to_csv(summary_csv, index=False)
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    plot_files = _write_plots(timeseries_df=timeseries_df, summary_df=summary_df, output_dir=output_dir)
    _write_report(
        report_path=report_markdown,
        config=config,
        summary_df=summary_df,
        plot_files=plot_files,
    )

    return DenseAnalysisArtifacts(
        output_dir=output_dir,
        manifest_path=manifest_path,
        timeseries_csv=timeseries_csv,
        summary_csv=summary_csv,
        report_markdown=report_markdown,
        plot_files=tuple(plot_files),
    )



def _result_to_rows(result: SimulationResult, *, reference_state: np.ndarray, delay: int) -> tuple[list[dict[str, float | int | str | bool]], dict[str, float | int | str | bool]]:
    """Convert a simulation result into timeseries and summary rows."""
    rows: list[dict[str, float | int | str | bool]] = []
    trace_distances: list[float] = []
    purities: list[float] = []
    entropies: list[float] = []
    source_norms: list[float] = []
    curvature_norms: list[float] = []

    for record in result.records:
        state = ensure_density(np.asarray(record.state, dtype=np.complex128))
        trace_distance = _trace_distance(state, reference_state)
        purity = float(np.trace(state @ state).real)
        entropy = _von_neumann_entropy(state)
        source_norm = float(np.linalg.norm(record.source))
        curvature_norm = float(np.linalg.norm(record.curvature))
        effective_source_norm = float(np.linalg.norm(record.effective_source))
        trace_distances.append(trace_distance)
        purities.append(purity)
        entropies.append(entropy)
        source_norms.append(source_norm)
        curvature_norms.append(curvature_norm)
        rows.append(
            {
                "delay_steps": int(delay),
                "time": float(record.time),
                "trace_distance_to_reference": trace_distance,
                "purity": purity,
                "entropy": entropy,
                "source_norm": source_norm,
                "effective_source_norm": effective_source_norm,
                "curvature_norm": curvature_norm,
                "buffer_advance_count": int(record.buffer_advance_count),
                "history_length": int(record.history_length),
            }
        )

    summary = {
        "delay_steps": int(delay),
        "final_trace_distance_to_reference": float(trace_distances[-1]),
        "max_trace_distance_to_reference": float(np.max(trace_distances)),
        "final_purity": float(purities[-1]),
        "min_purity": float(np.min(purities)),
        "final_entropy": float(entropies[-1]),
        "max_entropy": float(np.max(entropies)),
        "final_source_norm": float(source_norms[-1]),
        "max_source_norm": float(np.max(source_norms)),
        "final_curvature_norm": float(curvature_norms[-1]),
        "max_curvature_norm": float(np.max(curvature_norms)),
        "num_records": int(len(rows)),
    }
    return rows, summary



def _trace_distance(rho: np.ndarray, sigma: np.ndarray) -> float:
    """Compute the trace distance between two density matrices."""
    delta = 0.5 * ((rho - sigma) + np.conjugate((rho - sigma).T))
    evals = np.linalg.eigvalsh(delta).real
    return float(0.5 * np.sum(np.abs(evals)))



def _von_neumann_entropy(rho: np.ndarray) -> float:
    """Compute the von Neumann entropy in nats."""
    evals = np.linalg.eigvalsh(rho).real
    evals = np.clip(evals, 1e-12, None)
    evals /= np.sum(evals)
    return float(-np.sum(evals * np.log(evals)))



def _write_plots(timeseries_df: pd.DataFrame, summary_df: pd.DataFrame, output_dir: Path) -> list[Path]:
    """Write interactive Plotly visualizations."""
    plot_files: list[Path] = []

    plot_specs = [
        ("source_norm", "Source Norm Over Time", "source_norm_vs_time.html"),
        ("curvature_norm", "Curvature Norm Over Time", "curvature_norm_vs_time.html"),
        ("purity", "Purity Over Time", "purity_vs_time.html"),
        ("entropy", "Entropy Over Time", "entropy_vs_time.html"),
        ("trace_distance_to_reference", "Trace Distance To Reference Over Time", "trace_distance_vs_time.html"),
    ]

    for y_axis, title, filename in plot_specs:
        fig = px.line(
            timeseries_df,
            x="time",
            y=y_axis,
            color="delay_steps",
            markers=True,
            title=title,
            labels={"delay_steps": "Delay Steps", y_axis: y_axis.replace("_", " ").title()},
        )
        fig.update_layout(template="plotly_white")
        path = output_dir / filename
        fig.write_html(path, include_plotlyjs="cdn")
        plot_files.append(path)

    bar_fig = go.Figure()
    bar_fig.add_bar(x=summary_df["delay_steps"], y=summary_df["final_trace_distance_to_reference"], name="Final trace distance")
    bar_fig.add_bar(x=summary_df["delay_steps"], y=summary_df["final_entropy"], name="Final entropy")
    bar_fig.update_layout(
        title="Final Delay-Dependent Summary Metrics",
        xaxis_title="Delay Steps",
        yaxis_title="Metric Value",
        barmode="group",
        template="plotly_white",
    )
    summary_plot = output_dir / "summary_metrics.html"
    bar_fig.write_html(summary_plot, include_plotlyjs="cdn")
    plot_files.append(summary_plot)

    return plot_files



def _dataframe_to_markdown(frame: pd.DataFrame) -> str:
    """Render a Markdown table without optional pandas dependencies."""
    headers = [str(column) for column in frame.columns]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in frame.itertuples(index=False, name=None):
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return "\n".join(lines)


def _write_report(report_path: Path, config: DenseAnalysisConfig, summary_df: pd.DataFrame, plot_files: list[Path]) -> None:
    """Write the Markdown report in English."""
    best_delay_row = summary_df.loc[summary_df["final_trace_distance_to_reference"].idxmin()]
    worst_delay_row = summary_df.loc[summary_df["final_trace_distance_to_reference"].idxmax()]
    summary_table_df = summary_df[[
        "delay_steps",
        "final_trace_distance_to_reference",
        "max_trace_distance_to_reference",
        "final_purity",
        "final_entropy",
        "final_source_norm",
        "final_curvature_norm",
    ]].round(6)
    summary_table = _dataframe_to_markdown(summary_table_df)

    final_trace_span = float(summary_df["final_trace_distance_to_reference"].max() - summary_df["final_trace_distance_to_reference"].min())
    final_entropy_span = float(summary_df["final_entropy"].max() - summary_df["final_entropy"].min())
    delay_sensitive = (final_trace_span > 1e-9) or (final_entropy_span > 1e-9)

    lines = [
        "# Dense Delay Analysis Report",
        "",
        "## Objective",
        "",
        "This analysis evaluates how the pure-delay feedback parameter modifies the behavior of the reduced dense-state OCTA model.",
        "The goal is to inspect the delay dependence of the modular source, effective curvature response, and state-space diagnostics while preserving audited causal semantics.",
        "",
        "## Configuration",
        "",
        f"- Delays analysed: {', '.join(str(x) for x in config.delays)}",
        f"- Total time: {config.total_time}",
        f"- Time step: {config.dt}",
        f"- Seed: {config.seed}",
        "- Model family: reduced dense OCTA model on graph balls.",
        "",
        "## Generated Artifacts",
        "",
    ]
    for plot in plot_files:
        lines.append(f"- {plot.name}")
    lines.extend([
        "- dense_delay_timeseries.csv",
        "- dense_delay_summary.csv",
        "- manifest.json",
        "",
        "## Summary Table",
        "",
        summary_table,
        "",
        "## Result Assessment",
        "",
        f"The smallest final trace distance to the reference state is obtained at `delay_steps = {int(best_delay_row['delay_steps'])}` with value `{best_delay_row['final_trace_distance_to_reference']:.6f}`.",
        f"The largest final trace distance is obtained at `delay_steps = {int(worst_delay_row['delay_steps'])}` with value `{worst_delay_row['final_trace_distance_to_reference']:.6f}`.",
        (
            "In this run the delay sweep is effectively degenerate at the summary-metric level: the final trace-distance and final-entropy spans across delays are below numerical relevance, so the present reduced dense model is not yet expressing a visible delay dependence for these settings."
            if not delay_sensitive
            else "The delay sweep shows nontrivial separation in the summary metrics, so the interactive plots should be used to identify whether the difference is transient, persistent, or dominated by mixing."
        ),
        "The purity and entropy plots are especially useful for distinguishing genuine dynamical separation from changes dominated by local mixing.",
        "",
        "## Interpretation Notes",
        "",
        "- If a delay value lowers both the final trace distance and the peak trace distance, it is a stronger candidate for improved alignment with the reference dynamics.",
        "- If entropy rises rapidly while the trace distance contracts, the apparent agreement may be partially explained by mixing rather than by detailed dynamical agreement.",
        "- Source-norm and curvature-norm trajectories indicate whether the delay acts mainly on the forcing term or on the downstream geometric response.",
        "",
        "## Limitations",
        "",
        "This report is generated from the reduced dense-state OCTA model and is intended as a controlled PoC rather than a full high-fidelity production workflow.",
        "The dense model is designed to preserve the core delay semantics while remaining computationally controlled and reproducible.",
        "",
        "## Next Step",
        "",
        "The next recommended step is to enrich the reduced model and expand the sweep protocol while preserving the same delay-buffer and audit contracts.",
    ])
    report_path.write_text("\n".join(lines), encoding="utf-8")
